```typescript
import { Graph } from '../data-structures/Graph';
import { PriorityQueue } from '../data-structures/PriorityQueue';

/**
 * Finds the shortest path (minimum total weight) from a single source node
 * to all other reachable nodes in a weighted graph with non-negative edge weights
 * using Dijkstra's algorithm.
 *
 * Time Complexity: O((V + E) log V) with a binary heap priority queue.
 *   - V: Number of vertices, E: Number of edges.
 *   - Each vertex is inserted/extracted from the priority queue at most once: V * log V.
 *   - Each edge causes a potential update/insertion into the priority queue: E * log V.
 *   - Therefore, (V + E) log V.
 * Space Complexity: O(V + E)
 *   - `distances`: Stores V entries.
 *   - `parentMap`: Stores V entries.
 *   - `priorityQueue`: Stores at most E entries (if re-inserting) or V entries (if `decreaseKey` is perfect).
 *     Since our PriorityQueue re-inserts for "decreaseKey", it can store up to E entries in worst case.
 *
 * @param graph - The graph to search within (must be a weighted graph with non-negative weights).
 * @param startNode - The starting node for the path.
 * @returns An object containing:
 *   - `distances`: A Map where keys are nodes and values are the shortest distance from startNode.
 *   - `parentMap`: A Map where keys are nodes and values are their predecessors in the shortest path.
 *                 Can be used to reconstruct the full path to any node.
 */
export function dijkstra<T extends string | number>(
    graph: Graph<T>,
    startNode: T
): { distances: Map<T, number>; parentMap: Map<T, T | null> } {
    // 1. Validate start node
    if (!graph.hasNode(startNode)) {
        console.warn(`Dijkstra: Start node ${startNode} not found in graph.`);
        return { distances: new Map(), parentMap: new Map() };
    }

    // Map to store the shortest distance found so far from `startNode` to every other node.
    // Initialize with Infinity for all nodes except `startNode`.
    const distances: Map<T, number> = new Map();
    // Map to reconstruct the shortest path: maps a node to its predecessor.
    const parentMap: Map<T, T | null> = new Map();
    // Priority Queue to always extract the node with the smallest known distance.
    const pq = new PriorityQueue<T>();

    // Initialize distances: All nodes initially have 'infinity' distance, except startNode.
    // All nodes have no parent initially.
    for (const node of graph.getNodes()) {
        distances.set(node, Infinity);
        parentMap.set(node, null);
    }
    distances.set(startNode, 0);

    // Add the start node to the priority queue with distance 0.
    pq.insert(startNode, 0);

    // Dijkstra's main loop
    while (!pq.isEmpty()) {
        const { value: currentNode, priority: currentDistance } = pq.extractMin()!;

        // IMPORTANT: Check if we've found a shorter path to `currentNode` already.
        // This handles cases where a node is inserted multiple times into the PQ
        // (because our PQ doesn't have an efficient `decreaseKey` that removes older entries).
        // If the current extracted distance is greater than the already recorded shortest distance,
        // it means we found a shorter path earlier, so this is a stale entry.
        if (currentDistance > distances.get(currentNode)!) {
            continue;
        }

        // Iterate over all neighbors of the current node
        for (const { neighbor, weight } of graph.getNeighbors(currentNode)) {
            // Calculate the distance to the neighbor through the currentNode
            const newDistance = currentDistance + weight;

            // If this new path to the neighbor is shorter than the previously known shortest path
            if (newDistance < distances.get(neighbor)!) {
                // Update the shortest distance for the neighbor
                distances.set(neighbor, newDistance);
                // Set the current node as the parent of the neighbor for path reconstruction
                parentMap.set(neighbor, currentNode);
                // Add/update the neighbor in the priority queue with its new, shorter distance.
                // (Our PQ will insert, relying on the `currentDistance > distances.get(currentNode)` check above for stale entries).
                pq.insert(neighbor, newDistance);
            }
        }
    }

    return { distances, parentMap };
}

/**
 * Helper function to reconstruct the shortest path from the start node to a specific end node
 * using the `parentMap` generated by Dijkstra's algorithm.
 *
 * @param startNode - The starting node.
 * @param endNode - The target node.
 * @param parentMap - The parent map generated by Dijkstra's algorithm.
 * @returns An array of nodes representing the shortest path from startNode to endNode.
 *          Returns an empty array if no path exists or endNode is unreachable.
 */
export function reconstructPathDijkstra<T extends string | number>(
    startNode: T,
    endNode: T,
    parentMap: Map<T, T | null>
): T[] {
    const path: T[] = [];
    let currentNode: T | null = endNode;

    // Traverse back from endNode using the parentMap
    while (currentNode !== null && parentMap.has(currentNode)) {
        path.unshift(currentNode); // Add to the beginning of the path
        if (currentNode === startNode) break; // Path found
        currentNode = parentMap.get(currentNode)!; // Move to the parent
    }

    // If the path doesn't start with the startNode (and it's not the startNode itself),
    // it means endNode was unreachable from startNode.
    if (path.length === 0 || path[0] !== startNode) {
        return [];
    }

    return path;
}
```