const { Graph } = require('../data-structures/Graph');
const PriorityQueue = require('../data-structures/PriorityQueue');

/**
 * Implements Dijkstra's algorithm to find the shortest paths from a single source vertex
 * to all other reachable vertices in a weighted graph with non-negative edge weights.
 *
 * @param {Graph} graph - The graph to analyze. Must have non-negative edge weights.
 * @param {*} startVertex - The starting vertex for shortest path calculations.
 * @returns {{distances: Map<*, number>, paths: Map<*, *>}} An object containing:
 *   - `distances`: A Map where keys are vertices and values are their shortest distance from `startVertex`.
 *   - `paths`: A Map where keys are vertices and values are their predecessors in the shortest path.
 *   Returns null if the `startVertex` does not exist in the graph.
 *
 * Time Complexity: O(E log V) if using a binary heap (PriorityQueue),
 *   where V is the number of vertices and E is the number of edges.
 *   Each edge relaxation takes O(log V) time (enqueue or updatePriority). Each vertex extracted once (log V).
 * Space Complexity: O(V + E) for storing distances, paths, and the priority queue.
 */
function dijkstra(graph, startVertex) {
    if (!graph.hasVertex(startVertex)) {
        console.warn(`Dijkstra: Start vertex '${startVertex}' not found in graph.`);
        return null;
    }

    /**
     * Stores the shortest distance from `startVertex` to each other vertex.
     * Initialized to Infinity for all vertices except `startVertex` (0).
     * @type {Map<*, number>}
     */
    const distances = new Map();
    /**
     * Stores the predecessor of each vertex in the shortest path found so far.
     * Used to reconstruct the actual paths.
     * @type {Map<*, *>}
     */
    const paths = new Map();
    /**
     * Priority Queue to efficiently retrieve the unvisited vertex with the smallest distance.
     */
    const pq = new PriorityQueue();

    // Initialize distances: all to Infinity, startVertex to 0
    // Initialize paths: all to null
    for (const vertex of graph.getVertices()) {
        distances.set(vertex, Infinity);
        paths.set(vertex, null);
    }
    distances.set(startVertex, 0);

    // Enqueue the start vertex with priority 0
    pq.enqueue(startVertex, 0);

    while (!pq.isEmpty()) {
        // Get the vertex with the smallest distance from the priority queue
        const { element: currentVertex, priority: currentDistance } = pq.dequeue();

        // Optimization: if we've already found a shorter path to currentVertex, skip
        // This can happen if an element was enqueued multiple times before updating
        // its priority (if PQ implementation doesn't remove duplicates efficiently).
        // Our PQ implementation supports `updatePriority`, so this check primarily
        // guards against stale entries if `updatePriority` wasn't fully used.
        if (currentDistance > distances.get(currentVertex)) {
            continue;
        }

        // Iterate over neighbors of the current vertex
        for (const edge of graph.getNeighbors(currentVertex)) {
            const neighbor = edge.neighbor;
            const weight = edge.weight;

            // Calculate the distance to the neighbor through the current vertex
            const distanceThroughCurrent = currentDistance + weight;

            // If a shorter path to the neighbor is found
            if (distanceThroughCurrent < distances.get(neighbor)) {
                distances.set(neighbor, distanceThroughCurrent); // Update distance
                paths.set(neighbor, currentVertex);             // Update predecessor
                pq.enqueue(neighbor, distanceThroughCurrent);   // Enqueue/update neighbor in PQ
            }
        }
    }

    return { distances, paths };
}

/**
 * Helper function to reconstruct the shortest path from the `paths` map generated by Dijkstra's.
 *
 * @param {Map<*, *>} paths - The `paths` map from Dijkstra's algorithm.
 * @param {*} startVertex - The starting vertex.
 * @param {*} endVertex - The target vertex.
 * @returns {Array<*> | null} An array of vertices representing the shortest path, or null if no path exists.
 *
 * Time Complexity: O(V) in the worst case (a path through all vertices).
 * Space Complexity: O(V) for the path array.
 */
function reconstructPath(paths, startVertex, endVertex) {
    if (!paths.has(endVertex) || paths.get(endVertex) === null && endVertex !== startVertex) {
        return null; // No path to endVertex
    }
    const path = [];
    let current = endVertex;
    while (current !== null) {
        path.unshift(current);
        if (current === startVertex) break; // Stop when start is reached
        current = paths.get(current);
    }
    // If we started from endVertex and only reached startVertex, it's a valid path.
    // If current is not startVertex and paths.get(current) became undefined/null before reaching startVertex,
    // it implies endVertex was unreachable from startVertex, but Dijkstra initialises with null for all
    // non-start nodes. So the first check should cover it.
    // An alternative check is `path[0] === startVertex`.
    return path[0] === startVertex ? path : null;
}


module.exports = {
    dijkstra,
    reconstructPath,
};